"""Draft 'I can' descriptors for AERO-SS K-5 indicators that have no school descriptors.
Tuple order: (advanced, at_target, approaching, emerging). "I can " is added by the build when missing.
"""
D = {
    "1.5.a": ("compare how people from two different times or places saw the same thing, and explain what caused the difference.",
              "explain why people in different times and places view the world differently, using an example.",
              "give one way people in the past or in another place saw the world differently, with help.",
              "say that people long ago lived and thought in different ways, using pictures."),
    "1.5.d": ("compare a primary and a secondary source about the same event and explain which is more useful and why.",
              "identify primary and secondary sources and use them to find out about the past and present.",
              "sort sources into primary or secondary with help and find one fact in a source.",
              "look at an old photo or object and say one thing it shows about the past."),
    "2.5.a": ("explain how my choices about wants and needs can affect my community and the environment over time.",
              "describe how wants and needs have effects beyond myself, on other people and places.",
              "give one example of how my wants or needs affect someone else, with help.",
              "sort pictures into wants and needs."),
    "3.2.a": ("explain how people in Qatar change the way they live because of the desert, the sea, or the weather.",
              "describe ways people depend on the physical environment for food, water, and shelter.",
              "name one thing people get from the land or sea, with help.",
              "point to pictures of land, water, and sky and say what people use them for."),
    "3.5.b": ("choose the best geographic tool for a question and explain why I chose it.",
              "use resources and geographic tools, such as maps, globes, and photos, to find and explain information about the earth.",
              "use one geographic tool with help to find a simple fact about a place.",
              "name a map or a globe and point to land and water."),
    "3.5.e": ("explain how several factors together influence where people live and why they migrate, using Qatar and another country.",
              "describe factors, such as water, jobs, and climate, that influence where people live and why they move.",
              "name one reason people live in a place or move away, with help.",
              "say where my family lives and one thing about that place."),
    "3.5.f": ("compare settlement and land-use patterns in two places and explain why they are different.",
              "describe and explain different types and patterns of settlement and land use, such as city, village, farm, and industry.",
              "identify one type of settlement or land use on a map, with help.",
              "point to houses, farms, or factories in pictures."),
    "3.5.g": ("explain why a location is a good or poor choice for an activity and suggest a better one.",
              "identify why particular locations are used for certain activities, such as ports near the sea.",
              "match an activity to a place where it happens, with help.",
              "name a place and one thing people do there."),
    "3.5.h": ("compare two regions and explain how their human and physical characteristics make them different.",
              "define regions by their human and physical characteristics.",
              "name one human or one physical characteristic of a region, with help.",
              "point to an area on a map and name one thing found there."),
    "4.2.c": ("compare how two cultures use resources, shelter, and transportation and explain why they are different.",
              "describe how people from different cultures interact with the environment, such as using resources, shelter, and transportation.",
              "give one example of how a culture uses the land or sea, with help.",
              "match pictures of homes or transport to the place where people use them."),
    "4.2.d": ("explain why social environments in two cultures are similar or different.",
              "compare and contrast social environments, such as homes, schools, and celebrations, in different cultures.",
              "name one thing that is the same or different between two cultures, with help.",
              "look at pictures of two cultures and point to something different."),
    "4.2.e": ("explain why behavior expectations are different in two cultures and how to show respect for both.",
              "describe how to act in my own culture and compare this with expectations in other cultures.",
              "name one rule for how to act in my culture, with help.",
              "show a polite way to greet someone in my culture."),
    "4.5.b": ("explain why different cultures meet the same need in different ways, using evidence.",
              "compare and contrast the ways different cultures meet human needs and concerns.",
              "give one way a culture meets a need such as food or shelter, with help.",
              "name basic needs such as food, water, and shelter."),
    "4.5.c": ("explain what a folktale or legend teaches about a culture's values and compare it with a story from Qatar.",
              "explain the main ideas in folktales, legends, songs, myths, and stories of heroism from different cultures.",
              "retell part of a folktale or legend and name its hero, with help.",
              "listen to a folktale and name one character."),
    "4.5.e": ("explain how the elements of culture connect to each other, using an example from Qatar.",
              "explain the elements of culture, such as language, norms, values, and beliefs.",
              "name two elements of culture and give an example of one, with help.",
              "name my language and one tradition my family has."),
    "4.5.f": ("compare the elements of two belief systems respectfully.",
              "define the elements of a belief system: creed, code of behavior, rituals, and community.",
              "match an element of a belief system to an example, with help.",
              "name one way people in my community show what they believe."),
    "4.5.g": ("explain how the main beliefs of a world religion guide people's daily lives.",
              "examine the main beliefs and practices of one major world religion.",
              "name one main belief or practice of a world religion, with help.",
              "name a place of worship or a special day of a religion."),
    "4.5.h": ("explain how a community can reduce the disadvantages and increase the benefits of cultural diversity.",
              "describe advantages and disadvantages of cultural diversity.",
              "give one advantage of people from different cultures living together, with help.",
              "name two cultures in my class or community."),
    "4.5.i": ("trace how a food, idea, or invention spread between cultures and explain its effects.",
              "examine cultural diffusion: how ideas, foods, and customs spread from one culture to another.",
              "give one example of something that came to Qatar from another culture, with help.",
              "name a food or object that comes from another country."),
    "5.2.d": ("explain how a behavior that is fine in one place may not be fine in another, and choose well.",
              "recognize appropriate and inappropriate social behavior in different places and explain the impact of my choices.",
              "sort behaviors into good and not good choices, with help.",
              "show one good behavior for the classroom."),
    "5.2.e": ("explain how living in groups such as family, community, and nation helps people meet needs.",
              "explain why people live in social groups, such as families, communities, and nations.",
              "name groups I belong to and say one reason people live together, with help.",
              "name the people in my family."),
    "5.2.f": ("explain how different roles in a group help the group succeed, and choose a role that fits a task.",
              "identify roles and behaviors that people show in group situations.",
              "name one role in a group, such as leader or helper, with help.",
              "take a turn in a group activity."),
    "5.2.g": ("explain how my choices, such as my interests and friends, help shape who I am.",
              "identify opportunities for choice in my personal identity.",
              "name one thing I can choose about myself, such as a hobby, with help.",
              "say one thing I like to do."),
    "5.5.b": ("explain how a person's background can shape how they see an event and why others may see it differently.",
              "identify how circumstances such as ethnicity, gender, and family background influence how a person sees and reacts to the world.",
              "give one example of how a person's background affects what they think, with help.",
              "say that people can feel differently about the same thing."),
    "5.5.c": ("explain why groups and cultures meet their members' needs in different ways.",
              "compare and contrast how groups and cultures meet the needs and concerns of their members.",
              "name one way a group helps its members, with help.",
              "name a group I belong to and one thing it does for me."),
    "5.5.d": ("compare how two institutions influence people and explain which affects me most and why.",
              "describe different institutions, such as schools, mosques, and clubs, and how they influence a person.",
              "name an institution and one thing it does, with help.",
              "name my school and one thing I learn there."),
    "5.5.f": ("explain how media, schools, or families can shape what people think about identity, and question it.",
              "identify how social systems such as schools, media, religions, and families shape people's identities.",
              "give one example of how family or school shapes who I am, with help.",
              "name people who help me learn how to behave."),
    "5.5.g": ("explain how socialization shapes me and which parts of my identity I can choose.",
              "describe socialization and the opportunities for choice in personal identity.",
              "name one thing I learned from my family or school about how to act, with help.",
              "say one thing about myself."),
    "5.5.h": ("explain how moving from tolerance to acceptance can improve a community, with an example.",
              "examine the difference between acceptance and tolerance.",
              "give an example of tolerance or of acceptance, with help.",
              "show kindness to someone who is different from me."),
    "6.2.c": ("explain how my rights and responsibilities in a group are connected.",
              "describe my rights and responsibilities in my social group and the qualities of a good citizen.",
              "name one right and one responsibility I have in class, with help.",
              "name one class rule."),
    "6.2.d": ("explain which leadership qualities matter most in a situation and why.",
              "identify qualities that leaders need to meet their responsibilities.",
              "name one quality of a good leader, with help.",
              "name a leader at school or at home."),
    "6.2.e": ("explain how my family and school work together to help me grow.",
              "describe the impact of my family and school on my life.",
              "name one way my family or school helps me, with help.",
              "name people in my family and my school."),
    "6.2.f": ("explain how a good citizen balances rights and responsibilities, using an example from my community.",
              "explain my rights and responsibilities in my social group, including the qualities of a good citizen.",
              "describe one right and one responsibility, with help.",
              "name a way to be a good helper in class."),
    "6.2.g": ("plan a small act of service and explain how it helps my community.",
              "explain reasons why leadership and service are important.",
              "give one example of leadership or service, with help.",
              "name someone who helps other people."),
    "6.2.h": ("use a fair way to solve a class problem and explain why it is fair.",
              "identify principles used for decision-making and problem solving, such as fairness, cooperation, and responsibility.",
              "name one fair way to make a decision, such as taking turns, with help.",
              "take turns with a partner."),
    "6.2.i": ("compare how two groups, such as a mosque and a government office, help my community.",
              "describe the impact of religious institutions, government agencies, and civic groups on my life.",
              "name one group or agency and one way it helps people, with help.",
              "name a place in my community that helps people."),
    "6.5.b": ("explain how a political institution in Qatar meets needs and suggest an improvement.",
              "describe how political institutions meet the needs and wants of people and society.",
              "name one institution and one need it meets, with help.",
              "name a government service such as hospitals or schools."),
    "6.5.c": ("explain the job of a community leader, a national official, and a world leader and how they connect.",
              "identify community leaders, local and national government officials, and world leaders.",
              "name one community leader and one national leader, with help.",
              "name a leader at my school."),
    "6.5.i": ("explain advantages and disadvantages of two political systems using evidence.",
              "compare and contrast major political systems, such as monarchy and democracy.",
              "name one difference between two political systems, with help.",
              "name the leader of Qatar."),
    "6.5.j": ("choose the best strategy for a conflict and explain why it works.",
              "explain different strategies to resolve conflict, such as talking, compromise, and mediation.",
              "name one way to solve a disagreement, with help.",
              "use calm words when I disagree."),
    "7.2.c": ("explain what would happen in my community if one specialized job disappeared.",
              "describe how we depend on people with specialized jobs.",
              "match a job to how it helps people, with help.",
              "name a job such as doctor or teacher."),
    "7.2.d": ("explain how goods and services work together, such as a mechanic using parts to fix a car.",
              "distinguish between goods and services.",
              "sort pictures into goods and services, with help.",
              "name something I can buy."),
    "7.2.e": ("explain the choice I would make with limited money and what I give up.",
              "explain why people make choices about how to satisfy wants and needs.",
              "say why someone might choose one thing over another, with help.",
              "choose between two things and say which I want."),
    "7.2.f": ("explain how banks, markets, and businesses work together in an economy.",
              "identify institutions that are part of economic systems, such as banks, markets, and businesses.",
              "name one economic institution and what it does, with help.",
              "name a shop or a bank."),
    "7.2.g": ("compare trading, buying with money, and buying online and explain which is best for a situation.",
              "describe how goods and services can be exchanged, such as by trading or using money.",
              "show how to trade or buy something in a role play, with help.",
              "name coins or notes used in Qatar."),
    "7.5.b": ("explain how human, natural, and capital resources combine to make a product.",
              "distinguish among human, natural, and capital resources.",
              "sort examples into human, natural, or capital resources, with help.",
              "name a natural resource such as water or oil."),
    "7.5.e": ("compare how trade affects jobs in Qatar and in another region.",
              "describe how trade affects the way people earn their living in regions of the world.",
              "name one job connected to trade, with help.",
              "name a product that comes from another country."),
    "7.5.f": ("explain why the division of labor changed as societies moved from hunting and gathering to farming to cities.",
              "describe changes in the division of labor from hunting and gathering to farming communities to urban societies.",
              "put pictures of hunting, farming, and city life in order and name one job in each, with help.",
              "name a job people do in a city."),
    "7.5.g": ("explain how several causes of world trade work together, using Qatar's gas exports as an example.",
              "describe the main causes of world trade.",
              "give one reason countries trade with each other, with help.",
              "say that countries buy and sell things to each other."),
    "8.2.c": ("design a simple tool for a problem and explain what it needs to work.",
              "identify reasons and requirements for making tools and developing techniques.",
              "say why someone made a tool, with help.",
              "name a tool and what it is used for."),
    "8.5.b": ("compare how a task is done with and without a tool and measure the difference.",
              "examine ways tools and techniques make certain tasks easier.",
              "give one example of a tool that makes a job easier, with help.",
              "use a simple tool in class."),
    "8.5.c": ("weigh the positive and negative effects of a technology and suggest how to reduce the negatives.",
              "describe ways tools and techniques can have both positive and negative effects.",
              "name one good effect and one bad effect of a tool, with help.",
              "say if a tool is helpful."),
    "8.5.e": ("explain how a scientific discovery changed people's values or beliefs over time, with evidence.",
              "describe times when new scientific or technological knowledge changed people's values, beliefs, and attitudes.",
              "give one example of how a new technology changed what people think, with help.",
              "name a new technology people use today."),
}

# Drafts for codes whose school descriptors describe a different standard (used as descriptors_suggested).
D.update({
    "1.2.a": ("retell a story about the past and explain what it teaches us about people or places.",
              "identify stories about past events, people, places, or situations.",
              "point to a picture in a story about the past and say who or what it shows, with help.",
              "listen to a story about long ago and name one person in it."),
    "6.2.a": ("explain how my rights and responsibilities help my class work well together.",
              "identify my rights and responsibilities in my class or family and the qualities of a good citizen.",
              "name one right and one responsibility I have in class, with help.",
              "follow one class rule."),
    "6.2.b": ("explain why we need people in authority and what makes their authority fair.",
              "identify people with authority, such as a teacher, principal, or the Emir, and say why they have it.",
              "match a person in authority to the place they lead, with help.",
              "name a person who is in charge at school."),
    "7.2.a": ("explain why I chose something as a need or a want and what happens if a need is not met.",
              "distinguish between needs and wants.",
              "sort pictures into needs and wants, with help.",
              "point to something I need, such as food or water."),
    "8.2.a": ("give an example of a tool and the technique used with it, and explain the difference.",
              "distinguish between a tool (an object) and a technique (a way of doing something).",
              "sort pictures into tools and ways of doing things, with help.",
              "name a tool I use."),
    "1.2.c": ("explain how a story about the past helps me understand how life in Qatar is different today.",
              "relate stories about past events, people, places, or situations to understand the past and present.",
              "say one way life in a story from the past is different from today, with help.",
              "listen to a story about the past and say what happened."),
    "2.2.c": ("explain which way of dealing with a disagreement works best and why.",
              "identify that some ways of dealing with disagreements work better than others.",
              "choose a good way to solve a disagreement from two choices, with help.",
              "use calm words when I disagree."),
    "3.2.b": ("explain the location of a place using direction words and a landmark, such as the Corniche.",
              "explain the concept of location using words like near, far, next to, north, and south.",
              "describe where something is using near or far, with help.",
              "point to where something is in my classroom."),
    "3.2.c": ("make my own simple map, table, or graph to show geographic information.",
              "use maps, graphs, tables, and diagrams to read and display geographic information.",
              "read one fact from a simple map or table, with help.",
              "point to land and water on a map."),
    "3.2.d": ("compare two landforms and explain how they are different.",
              "locate and distinguish between landforms such as deserts, coasts, hills, and islands.",
              "match pictures of landforms to their names, with help.",
              "point to sand or sea in a picture of Qatar."),
    "3.2.e": ("explain how landforms and features in Qatar, such as the coast, affect where people live and their culture.",
              "describe the influence of landforms and geographic features on where people live and their cultures.",
              "say why people live near the sea, with help.",
              "name a landform near my home."),
    "3.2.f": ("compare how two cultures adapt to a hot or a cold environment and explain why.",
              "describe how people from different cultures think about and adapt to the physical environment.",
              "name one way people in Qatar adapt to the heat, with help.",
              "say if a place is hot or cold."),
    "3.5.a": ("use map elements such as scale and a grid to find and describe places on a map and a globe.",
              "explain and use the elements of maps and globes, such as title, key, compass rose, and scale.",
              "find the title, key, and compass rose on a map, with help.",
              "point to a map and a globe."),
    "5.5.a": ("explain how my family's traditions and values influence the choices I make.",
              "describe how families influence the individual.",
              "name one thing I learned from my family, with help.",
              "name the people in my family."),
    "6.5.a": ("explain an issue about rights and responsibilities in my community and suggest a fair solution.",
              "identify issues involving rights, roles, and responsibilities of individuals in society.",
              "name one right and one responsibility people have in society, with help.",
              "name one rule in my community."),
    "2.5.b": ("compare causes and effects of conflict and cooperation in politics, economics, and culture, with examples.",
              "explain causes and effects of conflict and cooperation among individuals, groups, societies, and nations.",
              "name one cause and one effect of cooperation or conflict, with help.",
              "give an example of people working together."),
    "2.5.c": ("compare how trade, cultural exchange, and international organizations connect Qatar with other nations.",
              "explain the major ways groups, societies, and nations interact, such as trade, cultural exchange, and international organizations.",
              "name one way Qatar interacts with another country, with help.",
              "name a country that Qatar is friends with."),
    "3.5.c": ("use location, distance, direction, scale, movement, and region to solve a map problem.",
              "apply concepts such as location, distance, direction, scale, movement, and region.",
              "use a compass rose and a scale to describe two places on a map, with help.",
              "find Qatar on a map."),
    "7.5.c": ("explain how changes in shipping and the internet changed trade in Qatar over time.",
              "describe how changes in transportation and communication have affected trade and economic activities.",
              "name one way transport or communication helps trade, with help.",
              "name a way goods travel, such as by ship."),
})
