"""Draft 'I can' descriptors for WI-SS grades 9-12 ('h') indicators.
Tuple order: (advanced, at_target, approaching, emerging). US references are localised where the idea transfers.
"""
D = {
    "SS.Inq1.a.h": ("frame a complex research question that links three strands and justify why it needs investigation.",
                    "frame researchable, complex, open-ended questions that integrate several social studies strands.",
                    "write an open-ended research question in one strand using a frame.",
                    "ask an open question about a topic."),
    "SS.Inq1.b.h": ("write a full research proposal with supporting questions and evaluated sources.",
                    "construct supporting questions and identify the sources I will use in my research proposal.",
                    "list supporting questions and two sources for a research plan, with help.",
                    "list what I want to find out."),
    "SS.Inq2.a.h": ("gather evidence through several disciplinary lenses and perspectives and explain gaps in the evidence.",
                    "explore evidence from my own research through different disciplines and perspectives, using primary, secondary, and media sources.",
                    "gather primary and secondary sources on my topic from a given list.",
                    "find one source on my topic."),
    "SS.Inq2.b.h": ("weigh several sources and explain how author, context, audience, and purpose change their reliability.",
                    "analyze how the author, context, audience, and purpose affect a source's reliability, limits, and usefulness.",
                    "identify the author, audience, and purpose of a source.",
                    "say whether a source is primary or secondary."),
    "SS.Inq3.a.h": ("develop a defensible claim and refine it after testing it against counter-evidence.",
                    "develop a defensible claim, based on analysis of sources, that focuses my inquiry.",
                    "write a claim based on sources using a frame.",
                    "state a position on a question."),
    "SS.Inq3.b.h": ("support a claim with evidence from multiple perspectives and media and explain how they connect.",
                    "support a claim with evidence from sources representing multiple perspectives and media.",
                    "support a claim with evidence from two sources.",
                    "find evidence that relates to a claim."),
    "SS.Inq3.c.h": ("modify a claim based on weak or conflicting evidence and explain my reasoning.",
                    "analyze how far evidence supports a claim and modify the claim if needed.",
                    "explain whether evidence supports a claim.",
                    "match evidence to a claim."),
    "SS.Inq4.a.h": ("adapt my conclusions for audiences with different backgrounds and explain my choices.",
                    "communicate conclusions while considering how diverse audiences may interpret them.",
                    "present conclusions clearly to one audience.",
                    "state my conclusion."),
    "SS.Inq4.b.h": ("critique a claim considering cultural, economic, political, and historical influences and propose improvements.",
                    "examine a claim's strengths and weaknesses, including its evidence and the influences behind its perspective.",
                    "identify one strength and one weakness of a claim.",
                    "say if I agree with a claim and why."),
    "SS.Inq5.a.h": ("design and lead a civic action informed by social science research and evaluate its results.",
                    "explore civic engagement opportunities informed by the knowledge and methods of the social sciences.",
                    "plan one civic action on a local issue.",
                    "identify an issue that matters to my community."),
    "SS.BH1.a.h": ("design and conduct a small research study on a behavior and explain nature and nurture influences.",
                   "analyze biological and environmental factors that influence behavior and explain the role of nature and nurture.",
                   "describe one biological and one environmental influence on behavior.",
                   "define nature and nurture."),
    "SS.BH1.b.h": ("evaluate how discrimination affects identity using a developmental theory and evidence.",
                   "examine the effects of discrimination on identity and explore developmental theories in relation to cultural bias.",
                   "describe one developmental theory and how it relates to identity.",
                   "define discrimination."),
    "SS.BH2.a.h": ("evaluate factors behind cooperation and conflict in a real case and propose ways to build unity.",
                   "investigate how language and culture unify groups and evaluate factors that cause cooperation and conflict.",
                   "describe how language or culture unifies a group.",
                   "give an example of a group united by language."),
    "SS.BH2.b.h": ("critique two interpretations of how a culture interacts with its environment.",
                   "critique interpretations of how different cultures interact with their environment.",
                   "summarize one interpretation of a culture's relationship with its environment.",
                   "describe how one culture uses its environment."),
    "SS.BH3.a.h": ("evaluate how institutions shaped a culture in the past and today and recognize ethnocentrism in sources.",
                   "analyze how groups and institutions influence people, events, and cultures and recognize ethnocentrism.",
                   "describe how one institution influenced a culture.",
                   "define ethnocentrism."),
    "SS.BH4.a.h": ("evaluate a technology's purpose and its intended and unintended effects on two cultures.",
                   "evaluate the purpose of a technology and analyze its intended and unintended consequences for cultures.",
                   "describe the purpose and one consequence of a technology.",
                   "name a technology and its purpose."),
    "SS.Econ1.a.h": ("perform a marginal cost-benefit analysis and defend a decision for a real Qatari issue.",
                     "perform a cost-benefit analysis on a real situation, describing marginal costs and benefits.",
                     "list costs and benefits of a decision in a table.",
                     "define cost and benefit."),
    "SS.Econ1.b.h": ("evaluate how changing an incentive would change what is produced in a market.",
                     "evaluate how incentives determine what is produced and distributed in a competitive market.",
                     "explain how an incentive affects a producer's choice.",
                     "define incentive."),
    "SS.Econ2.a.h": ("connect product, labor, and financial markets in a circular flow model and explain it.",
                     "connect the roles of consumers and producers in product, labor, and financial markets and the factor market.",
                     "describe the product market and the factor market.",
                     "define consumer and producer."),
    "SS.Econ2.b.h": ("use supply and demand graphs to predict equilibrium changes and compare market structures.",
                     "explain how supply and demand set equilibrium price and quantity and compare degrees of competition.",
                     "read equilibrium price from a supply and demand graph.",
                     "define supply and demand."),
    "SS.Econ2.c.h": ("calculate costs, revenue, and profit and recommend a decision for a firm.",
                     "calculate costs of production and explain their role in decisions, and calculate revenue and profit.",
                     "calculate profit from given revenue and cost.",
                     "define revenue and cost."),
    "SS.Econ3.a.h": ("use economic indicators to forecast the economy and explain differences between groups.",
                     "assess how spending and production decisions set income, employment, and prices and use indicators to analyze the economy.",
                     "interpret one economic indicator such as inflation or unemployment.",
                     "name an economic indicator."),
    "SS.Econ3.b.h": ("evaluate how a central bank's interest-rate decision affects the money system and the economy.",
                     "evaluate the structure and functions of money in a national economy, including interest rates.",
                     "explain how interest rates affect borrowing.",
                     "name the functions of money."),
    "SS.Econ3.c.h": ("analyze real and nominal GDP data to identify a phase of the business cycle.",
                     "connect GDP components to the economy, tell real from nominal GDP, and compare phases of the business cycle.",
                     "label the phases of the business cycle on a graph.",
                     "define GDP."),
    "SS.Econ4.a.h": ("evaluate how values and events shaped an economic system and its effect on wealth distribution.",
                     "evaluate how values and beliefs shape economic systems and analyze how resource allocation affects wealth and income.",
                     "describe how one value, such as equity, shapes an economic system.",
                     "name types of economic systems."),
    "SS.Econ4.b.h": ("evaluate how economic institutions and property rights affect wages and living standards locally.",
                     "analyze the impact of economic institutions and property rights on a country and a local economy.",
                     "describe the role of one economic institution such as a central bank.",
                     "name an economic institution."),
    "SS.Econ4.c.h": ("justify a fiscal or monetary policy choice for a given economic situation.",
                     "evaluate types of taxes and benefits and justify fiscal and monetary policies to expand or contract the economy.",
                     "tell the difference between fiscal and monetary policy.",
                     "name one thing governments pay for."),
    "SS.Econ4.d.h": ("evaluate a policy's intended and unintended effects and its success in reducing inequality.",
                     "evaluate intended and unintended costs and benefits of government policies and efforts to address inequality.",
                     "identify one intended and one unintended effect of a policy.",
                     "define externality."),
    "SS.Econ4.e.h": ("analyze Qatar's comparative advantage in LNG and its effects on trade and society.",
                     "draw conclusions about the effects of specialization and trade and analyze comparative advantage.",
                     "explain comparative advantage with a simple example.",
                     "define specialization."),
    "SS.Geog1.a.h": ("use GIS or digital maps to analyze a real-world problem and evaluate the data used.",
                     "use printed and digital maps to answer geographic questions and explain how geospatial technologies are used.",
                     "use a digital map to answer a geographic question.",
                     "name a geospatial tool such as GPS."),
    "SS.Geog1.b.h": ("interpret several map types to explain how a geographic problem changed over time.",
                     "interpret maps and images to analyze geographic problems and changes over time.",
                     "describe a change shown on two maps from different years.",
                     "identify the type of a map."),
    "SS.Geog1.c.h": ("compare my mental map before and after an event and explain how digital tools improved it.",
                     "compare mental maps before and after an event and explain how digital mapping improves mental maps.",
                     "draw a mental map of a region and compare it to a real map.",
                     "draw a simple map from memory."),
    "SS.Geog2.a.h": ("evaluate a population policy using composition data and predict its effects.",
                     "evaluate population policies and analyze population compositions and their implications.",
                     "read a population pyramid and describe its shape.",
                     "define population composition."),
    "SS.Geog2.b.h": ("evaluate the impact of a major migration on physical and human systems, past and present.",
                     "evaluate the impact of major international migrations on physical and human systems.",
                     "describe one major international migration and one effect.",
                     "define migration."),
    "SS.Geog2.c.h": ("analyze the social impact of movement in two time periods and compare them.",
                     "analyze the social impact of the movement of people across time periods and places.",
                     "describe one social effect of people moving to a new place.",
                     "name a reason people move."),
    "SS.Geog2.d.h": ("propose solutions to spatial inequality caused by urbanization in a real city.",
                     "evaluate spatial inequality from urbanization and analyze the impact of rural decline and urbanization.",
                     "describe one effect of urbanization on a place.",
                     "define urbanization."),
    "SS.Geog3.a.h": ("evaluate competition for resources in a contested zone and how consumption differs by country.",
                     "evaluate how access to resources creates competition and assess why resource use differs between countries.",
                     "compare resource use in a developed and a developing country.",
                     "name a resource countries compete for."),
    "SS.Geog3.b.h": ("analyze how the global economy and supranational organizations shape a region's development.",
                     "analyze the evolution of the global economy and the role of supranational organizations.",
                     "describe the role of one supranational organization such as the UN or GCC.",
                     "name an international organization."),
    "SS.Geog4.a.h": ("explain how ideology, culture, and identity shape how people see places and events.",
                     "evaluate how culture and characteristics give a place meaning and how place-based identities shape events.",
                     "describe how physical and human features give a place meaning.",
                     "name a place with special meaning."),
    "SS.Geog5.a.h": ("evaluate the spatial consequences of a human action at several scales and propose solutions.",
                     "analyze intended and unintended spatial consequences of human actions on the environment at different levels.",
                     "describe one consequence of a human action on the environment.",
                     "name a human action that changes the environment."),
    "SS.Geog5.b.h": ("hypothesize the global effects of a change in human behavior and support it with evidence.",
                     "hypothesize how changes in human behavior can cause effects on a global scale.",
                     "describe one way a change in behavior affects the environment.",
                     "name a human behavior that affects the environment."),
    "SS.Hist1.a.h": ("evaluate long- and short-term causes from several perspectives and judge which mattered most.",
                     "evaluate events from different perspectives using sources and analyze intended and unintended, long- and short-term causes.",
                     "identify a long-term and a short-term cause of an event.",
                     "name a cause of a historical event."),
    "SS.Hist1.b.h": ("evaluate long- and short-term effects from several perspectives and judge which mattered most.",
                     "evaluate events from different perspectives using sources and analyze intended and unintended, long- and short-term effects.",
                     "identify a long-term and a short-term effect of an event.",
                     "name an effect of a historical event."),
    "SS.Hist2.a.h": ("use sources to argue why a pattern of continuity lasted through a turning point.",
                     "evaluate primary and secondary sources to analyze patterns of continuity across eras and places.",
                     "describe a pattern of continuity using one source.",
                     "name something that stayed the same over an era."),
    "SS.Hist2.b.h": ("use sources to argue what caused a turning point and how much changed.",
                     "evaluate primary and secondary sources to analyze patterns of change across eras and places.",
                     "describe a pattern of change using one source.",
                     "name something that changed over an era."),
    "SS.Hist2.c.h": ("evaluate how much the historical context shaped a change compared with other factors.",
                     "evaluate how the historical context influenced continuity or change.",
                     "describe the context of a historical change.",
                     "say when and where a change happened."),
    "SS.Hist3.a.h": ("analyze how a historical period explains a current issue and evaluate the comparison.",
                     "analyze significant historical periods and their relationship to present issues and events.",
                     "describe one link between a historical period and today.",
                     "name a historical period."),
    "SS.Hist3.b.h": ("create an argument about a current event using several historical perspectives as evidence.",
                     "evaluate historical perspectives to create evidence-based arguments about current events.",
                     "use one historical perspective to explain a current event.",
                     "describe a viewpoint on a current event."),
    "SS.Hist3.c.h": ("justify a prediction about a current event by comparing several historical examples.",
                     "evaluate and justify predictions about current events based on the past.",
                     "make a prediction about a current event using one historical example.",
                     "say what might happen next in a current event."),
    "SS.Hist4.a.h": ("compare how context shaped two sources about the same event.",
                     "analyze how the historical context influences a primary or secondary source.",
                     "describe the context of a source.",
                     "identify when and where a source was made."),
    "SS.Hist4.b.h": ("compare how audience shaped two sources and what each leaves out.",
                     "analyze how the intended audience influences a primary or secondary source.",
                     "identify the audience of a source and one effect on its content.",
                     "identify who a source was made for."),
    "SS.Hist4.c.h": ("evaluate how a source's purpose limits its use as evidence.",
                     "analyze the intended purpose of a specific primary or secondary source.",
                     "identify the purpose of a source with evidence.",
                     "say why a source was made."),
    "SS.Hist4.d.h": ("evaluate how point of view shapes a source and identify whose voices are missing.",
                     "analyze how the author's point of view influences a source and identify whose voices may be left out.",
                     "identify the author's point of view and one missing voice.",
                     "name the author of a source."),
    "SS.PS1.a.h": ("evaluate how a constitution balances protecting rights with limiting government power.",
                   "analyze how constitutionalism protects values, freedoms, and rights by defining and limiting government, and analyze sources of authority.",
                   "describe how a constitution limits government power.",
                   "define constitution."),
    "SS.PS1.b.h": ("evaluate founding documents and key court decisions in shaping a nation's government.",
                   "evaluate the contributions of founders and analyze foundational ideas and documents of a national government.",
                   "describe one founding idea from a national document.",
                   "name a founding document."),
    "SS.PS2.a.h": ("critique the struggle for rights and evaluate the tension between individual rights and security.",
                   "critique the struggle for suffrage and citizenship and analyze tensions between rights and the general welfare.",
                   "describe one movement that expanded rights.",
                   "define civil rights."),
    "SS.PS2.b.h": ("compare legal protections for citizens and noncitizens and model the election process.",
                   "assess differences in protections for citizens and noncitizens and show skills needed to participate in elections.",
                   "describe one difference between citizens and noncitizens.",
                   "define citizen."),
    "SS.PS2.c.h": ("evaluate the methods of rights groups and the role of the UDHR and NGOs in different countries.",
                   "analyze how courts and groups restricted or expanded rights and the role of the UDHR and NGOs.",
                   "describe the role of one NGO in protecting human rights.",
                   "name the Universal Declaration of Human Rights."),
    "SS.PS3.a.h": ("create and evaluate solutions to increase participation in public decisions.",
                   "create and evaluate solutions to increase voter or civic participation and evaluate my role in government.",
                   "suggest one way to increase participation.",
                   "name a way citizens participate."),
    "SS.PS3.b.h": ("evaluate how media, parties, and interest groups compete to influence policy.",
                   "evaluate the role of media in government and how civic institutions and competing interests shape change.",
                   "describe how the media influence public opinion.",
                   "name a civic institution."),
    "SS.PS3.c.h": ("evaluate the powers and limits of government from local to global and NGO levels.",
                   "evaluate the structure and functions of governments and political institutions from local to supranational levels.",
                   "describe the role of one national and one global institution.",
                   "name levels of government."),
    "SS.PS3.d.h": ("evaluate the effectiveness of a public policy and recommend changes with evidence.",
                   "evaluate the effectiveness of public policy actions and processes.",
                   "describe a public policy and its goal.",
                   "define public policy."),
    "SS.PS4.a.h": ("research claims and counterclaims and build an argument that rebuts the strongest counterclaim.",
                   "create arguments by researching and interpreting claims and counterclaims.",
                   "write an argument with a claim, evidence, and one counterclaim.",
                   "state a claim with a reason."),
    "SS.PS4.b.h": ("evaluate the long-term effects of a major political compromise.",
                   "analyze the effects of a political compromise with major historical impact.",
                   "describe a historical compromise and one effect.",
                   "define compromise."),
}
