"""Draft 'I can' descriptors for WI-SS grades 6-8 ('m') indicators.
Tuple order: (advanced, at_target, approaching, emerging). US/Wisconsin references are localised where helpful.
"""
D = {
    "SS.Inq1.a.m": ("formulate open-ended questions that connect two social studies disciplines and rank them for research value.",
                    "formulate open-ended questions for further research within one social studies discipline.",
                    "turn a closed question into an open-ended question with a question frame.",
                    "ask a simple who, what, or where question about a topic."),
    "SS.Inq1.b.m": ("plan an inquiry with supporting questions and a matched list of reliable resources.",
                    "identify additional questions that support my research and possible resources to guide the inquiry.",
                    "add one supporting question and one resource to a teacher's plan.",
                    "list what I already know and want to know about a topic."),
    "SS.Inq2.a.m": ("gather evidence from sources that show opposing perspectives and explain how they differ.",
                    "explore evidence from multiple reliable sources that represent a range of perspectives and media.",
                    "gather evidence from two teacher-suggested sources.",
                    "find one fact in a given source."),
    "SS.Inq2.b.m": ("compare the credibility of two sources and justify which I would use.",
                    "determine the credibility and usefulness of a source by considering factors such as author, date, and purpose.",
                    "use a checklist to judge if a source is reliable.",
                    "name the author and date of a source."),
    "SS.Inq3.a.m": ("develop a debatable claim and anticipate a counterclaim.",
                    "develop a debatable and defensible claim based on analysis of sources.",
                    "write a claim using a claim frame after reading sources.",
                    "state my opinion about a question."),
    "SS.Inq3.b.m": ("support a claim with evidence from several media types and explain why each source is reliable.",
                    "support a claim with evidence from multiple reliable sources across different media.",
                    "support a claim with two pieces of evidence, with help.",
                    "find one piece of evidence for a claim."),
    "SS.Inq3.c.m": ("revise my claim when the evidence does not fully support it and explain the change.",
                    "analyze how far evidence supports a claim and adjust the claim if it does not.",
                    "say whether evidence supports a claim and give one reason.",
                    "match evidence to a claim."),
    "SS.Inq4.a.m": ("choose and justify the best medium for my audience and purpose.",
                    "communicate conclusions using a variety of media such as videos, exhibits, papers, or web pages.",
                    "present conclusions using one medium and a template.",
                    "share a conclusion orally with a partner."),
    "SS.Inq4.b.m": ("critique others' claims for bias and suggest how to strengthen them.",
                    "analyze and evaluate the logic, relevance, and accuracy of others' claims, considering bias.",
                    "check a claim for relevance and accuracy using a checklist.",
                    "say if I agree or disagree with a claim."),
    "SS.Inq5.a.m": ("plan and carry out a civic action and evaluate its impact.",
                    "explore opportunities for personal or group civic engagement with local, national, or global impact.",
                    "describe one civic action people can take on an issue.",
                    "name an issue in my school or community."),
    "SS.BH1.a.m": ("explain how several factors combine to shape a person's thinking and behavior in a case study.",
                   "identify patterns such as culture, prior knowledge, family, peers, and school that influence a person's thinking and behavior.",
                   "name two influences on a person's behavior with examples.",
                   "name one thing that influences how I act."),
    "SS.BH1.b.m": ("analyze how identity factors affect interactions between people and suggest ways to build empathy.",
                   "analyze how culture, ethnicity, age, religion, gender, and social class affect a person's self-image, identity, and interactions.",
                   "describe how one identity factor affects self-image.",
                   "name parts of my own identity."),
    "SS.BH2.a.m": ("compare causes of cooperation and conflict between two peoples and suggest ways to build cooperation.",
                   "summarize the role culture plays in behavior and categorize factors that lead to cooperation and conflict among peoples.",
                   "sort factors into causes of cooperation or conflict, with help.",
                   "give one example of cooperation and one of conflict."),
    "SS.BH2.b.m": ("model how I learned parts of my culture and how I learn about other cultures.",
                   "model how people learn their culture through interaction and learn other cultures through communication, travel, and study.",
                   "describe one way people learn about another culture.",
                   "name one tradition I learned from my family."),
    "SS.BH3.a.m": ("trace how a local action in Qatar has global consequences and the reverse.",
                   "analyze how local actions can have global consequences and how global patterns affect local actions.",
                   "give one example of a local action with a global effect.",
                   "name a global issue that affects Qatar."),
    "SS.BH4.a.m": ("evaluate intended and unintended consequences of a technology for two societies.",
                   "differentiate between intended and unintended consequences of technologies and how they affect societies and cultures.",
                   "name one intended and one unintended effect of a technology.",
                   "name a technology and what it is for."),
    "SS.Econ1.a.m": ("explain why opportunity cost differs between two people and how scarcity shapes national choices.",
                     "predict opportunity costs of decisions and assess how limited resources affect the choices of people, businesses, and countries.",
                     "identify the opportunity cost of a simple decision.",
                     "explain that resources are limited."),
    "SS.Econ1.b.m": ("evaluate whether an incentive will change household decisions and predict side effects.",
                     "evaluate how incentives affect individual and household decision making.",
                     "explain how one incentive changes a decision.",
                     "name an incentive, such as a discount."),
    "SS.Econ2.a.m": ("explain how households act as both consumers and producers in different markets.",
                     "analyze the role of consumers and producers in product markets with examples.",
                     "describe one way consumers and producers interact.",
                     "tell the difference between a consumer and a producer."),
    "SS.Econ2.b.m": ("use a simple supply and demand graph to predict price changes and explain competition effects.",
                     "investigate the relationship between supply and demand and evaluate how competition affects price and quality.",
                     "explain what happens to price when demand rises.",
                     "define supply and demand."),
    "SS.Econ2.c.m": ("explain how a business could change its mix of production factors to raise profit.",
                     "categorize factors of production and evaluate how profits influence sellers.",
                     "sort examples into land, labor, capital, and entrepreneurship.",
                     "name what is needed to make a product."),
    "SS.Econ3.a.m": ("compare how inflation and unemployment affect two different groups and explain why.",
                     "analyze how inflation, deflation, and unemployment affect different groups.",
                     "explain what inflation means using a price example.",
                     "say that prices can go up over time."),
    "SS.Econ3.b.m": ("explain how a change in interest rates would affect a saver and a borrower.",
                     "differentiate between the functions of money and assess how interest rates influence borrowing and investing.",
                     "name the three functions of money with examples.",
                     "say why people use money."),
    "SS.Econ3.c.m": ("explain what GDP comparisons show and do not show about life in two countries.",
                     "define Gross Domestic Product (GDP) and compare the GDP of different nations.",
                     "read GDP figures for two countries from a chart.",
                     "say that GDP measures what a country produces."),
    "SS.Econ4.a.m": ("evaluate which economic system best answers what, how, and for whom to produce in a case.",
                     "compare and contrast how traditional, command, market, and mixed economies allocate resources.",
                     "match an economic system to its description.",
                     "name one type of economic system."),
    "SS.Econ4.b.m": ("analyze how a rule or law protects both consumers and workers in Qatar.",
                     "compare economic institutions such as banks and businesses and analyze rules that protect consumers and workers.",
                     "describe the role of one economic institution.",
                     "name a bank or a business."),
    "SS.Econ4.c.m": ("evaluate the effect of a government spending decision on different groups.",
                     "analyze the impact of government policies such as taxes and spending on the economy.",
                     "describe one way government spending affects people.",
                     "name something the government spends money on."),
    "SS.Econ4.d.m": ("predict externalities of a proposed local law and suggest changes.",
                     "analyze possible unintended costs and benefits (externalities) of a local or national law or policy.",
                     "identify one externality of a policy with help.",
                     "name one effect of a rule."),
    "SS.Econ4.e.m": ("explain how specialization and trade affect prices of Qatar's imports and exports.",
                     "summarize the role of specialization in trade and cost and identify examples of exports and imports.",
                     "sort products into imports and exports for Qatar.",
                     "name one thing Qatar exports."),
    "SS.Geog1.a.m": ("compare map projections and explain which is best for a given question.",
                     "use paper and digital maps to answer geographic questions and analyze how map projections distort shape and size.",
                     "use a map to answer a where question.",
                     "find a country on a world map."),
    "SS.Geog1.b.m": ("interpret patterns across several thematic maps and explain how they are related.",
                     "interpret patterns in maps, charts, and graphs and explain relationships among them.",
                     "describe one pattern on a thematic map.",
                     "read the title and key of a map."),
    "SS.Geog1.c.m": ("draw a world mental map from memory and compare it with an accurate map.",
                     "construct a mental map of world regions with physical and cultural features and compare mental maps.",
                     "label continents, oceans, and major regions on a blank map.",
                     "name the continents."),
    "SS.Geog2.a.m": ("explain why population is rising in one region and falling in another, using data.",
                     "analyze why populations increase or decrease in world regions and analyze population patterns at different scales.",
                     "describe a population pattern on a map.",
                     "say which places have many people."),
    "SS.Geog2.b.m": ("compare migration patterns of two groups and explain the reasons.",
                     "analyze patterns of migration of different groups in the community, country, and world.",
                     "describe one migration pattern using a map.",
                     "name a reason people migrate."),
    "SS.Geog2.c.m": ("evaluate how migration changed both the place of origin and the place of settlement.",
                     "use world regions to analyze how population shifts change places and evaluate the impact of migration.",
                     "describe one way migration changes a place.",
                     "say that migration changes places."),
    "SS.Geog2.d.m": ("compare urbanization in Qatar with another region and predict future changes.",
                     "investigate the impact of rural decline and city growth and analyze patterns of urbanization worldwide.",
                     "describe one effect of a city growing.",
                     "tell the difference between rural and urban."),
    "SS.Geog3.a.m": ("explain how the location of resources shaped settlement in the Gulf now and in the past.",
                     "analyze the relationship between the distribution of resources and patterns of human settlement.",
                     "describe where one resource is found and who lives near it.",
                     "name a natural resource in the Gulf."),
    "SS.Geog3.b.m": ("analyze how the movement of people, products, and ideas links Qatar to world regions.",
                     "analyze spatial patterns of development and identify how people, products, and ideas move between places.",
                     "give one example of how products or ideas move between countries.",
                     "name a way products travel."),
    "SS.Geog4.a.m": ("explain how direct and indirect sources shape stereotypes about a place and challenge one.",
                     "explain how place-based identities change over time and can lead to stereotypes, comparing direct and indirect views of a place.",
                     "describe how a place's identity is linked to its characteristics.",
                     "name what my city is known for."),
    "SS.Geog5.a.m": ("evaluate how a technology both helps and burdens natural resources in Qatar.",
                     "analyze how technology interacts with the environment and affects the use of natural resources.",
                     "give one example of a technology that affects the environment.",
                     "name a natural resource."),
    "SS.Geog5.b.m": ("explain how unequal resources create trade and also conflict between countries.",
                     "analyze how the distribution of natural resources creates trade and how unequal distribution can cause conflict.",
                     "describe how one resource is traded between groups.",
                     "name a resource that countries trade."),
    "SS.Hist1.a.m": ("compare causes of similar events in two time periods using multiple perspectives.",
                     "use multiple perspectives to analyze and explain the causes of events across time periods or cultures.",
                     "explain two causes of a historical event.",
                     "name one cause of a historical event."),
    "SS.Hist1.b.m": ("compare effects of an event on different groups and explain why they differ.",
                     "use multiple perspectives to analyze and explain the effects of events across time periods or cultures.",
                     "explain two effects of a historical event.",
                     "name one effect of a historical event."),
    "SS.Hist2.a.m": ("explain why a pattern of continuity lasted across several regions.",
                     "explain patterns of continuity over time in the community, country, and world.",
                     "describe one pattern of continuity with an example.",
                     "name something that has stayed the same over time."),
    "SS.Hist2.b.m": ("explain why patterns of change happened at different speeds in different places.",
                     "explain patterns of change over time in the community, country, and world.",
                     "describe one pattern of change with an example.",
                     "name something that has changed over time."),
    "SS.Hist2.c.m": ("evaluate how much the historical context shaped a specific change.",
                     "analyze how historical context influenced the continuity or change that took place.",
                     "describe the context of a historical event.",
                     "say when and where an event happened."),
    "SS.Hist3.a.m": ("explain how a past event helps me understand a current world issue, using evidence.",
                     "compare events from world history to a current issue or event.",
                     "name one similarity between a past event and a current event.",
                     "name a current event."),
    "SS.Hist3.b.m": ("use historical perspectives to explain why people disagree about a current event.",
                     "apply historical perspectives to describe differing viewpoints of current events.",
                     "describe two viewpoints about a current event.",
                     "say what one person thinks about an event."),
    "SS.Hist3.c.m": ("make an evidence-based prediction about a current event and explain my reasoning.",
                     "hypothesize the direction and outcomes of current events based on the past.",
                     "make a prediction about a current event using a past example, with help.",
                     "say what might happen next in a news story."),
    "SS.Hist4.a.m": ("explain how a different context might have changed what a source says.",
                     "explain how the historical context influences a primary or secondary source.",
                     "describe the context of a source.",
                     "say when a source was made."),
    "SS.Hist4.b.m": ("compare how two sources on one event changed their message for different audiences.",
                     "explain the significance of the intended audience of a primary or secondary source.",
                     "identify the audience of a source and one effect on its message.",
                     "say who a source was made for."),
    "SS.Hist4.c.m": ("explain how a source's purpose affects its reliability as evidence.",
                     "explain the significance of the intended purpose of a primary or secondary source.",
                     "identify the purpose of a source.",
                     "say what a source is about."),
    "SS.Hist4.d.m": ("compare points of view in two sources and explain how each shapes meaning.",
                     "explain how the author's point of view can influence the meaning of a source.",
                     "identify the author's point of view in a source.",
                     "name the author of a source."),
    "SS.PS1.a.m": ("evaluate how rule of law and responsible citizenship protect a community, with examples.",
                   "investigate the parts of responsible citizenship and summarize the importance of the rule of law.",
                   "describe one part of responsible citizenship.",
                   "name a law in Qatar."),
    "SS.PS1.b.m": ("defend why a historical figure's contribution shaped my country's political culture and founding principles.",
                   "hypothesize why a historical person's contribution was important and investigate how founding principles have been applied over time.",
                   "describe one contribution of a founding figure.",
                   "name a founding figure of Qatar."),
    "SS.PS2.a.m": ("analyze how laws and court decisions expanded rights and how groups worked to extend them.",
                   "analyze the scope and limits of individual protections and describe how rights have changed over time.",
                   "describe one right protected by law.",
                   "name one human right."),
    "SS.PS2.b.m": ("compare how citizenship differs across types of government and explain why.",
                   "analyze citizens' rights and responsibilities and explain differing ideas of citizenship across governments.",
                   "list two rights and two responsibilities of citizens.",
                   "name one responsibility of a citizen."),
    "SS.PS2.c.m": ("compare how groups have advocated for rights in two countries and their results.",
                   "compare the status of marginalized groups past and present and investigate how groups advocate for rights.",
                   "describe one group that worked for greater rights.",
                   "say what fair treatment means."),
    "SS.PS3.a.m": ("explain how citizens participate in government at different levels and evaluate participation data.",
                   "assess participation in elections or public decisions and explain my role in government at different levels.",
                   "describe one way people participate in government.",
                   "name one level of government."),
    "SS.PS3.b.m": ("analyze how media and civic institutions influence government decisions, with examples.",
                   "analyze the role of media, elections, and civic institutions in connecting people to government.",
                   "describe one way the media informs people about government.",
                   "name a news source."),
    "SS.PS3.c.m": ("compare the powers and limits of government at two levels and explain why limits matter.",
                   "analyze the structure, functions, powers, and limits of government at different levels.",
                   "describe the main job of one government body.",
                   "name a government body in Qatar."),
    "SS.PS3.d.m": ("evaluate a public policy solution and suggest improvements.",
                   "analyze how governments solve problems through the public policy process.",
                   "describe the steps of the policy process with a diagram.",
                   "name a problem a government is trying to solve."),
    "SS.PS4.a.m": ("build an argument from multiple sources and rebut a counterargument.",
                   "assemble an argument using multiple sources of information.",
                   "write an argument with one claim and two pieces of evidence.",
                   "give my opinion with one reason."),
    "SS.PS4.b.m": ("explain how diplomacy or consensus solved a real conflict.",
                   "give examples of diplomacy, pluralism, and consensus building among people, groups, and institutions.",
                   "give one example of diplomacy or consensus.",
                   "define compromise."),
}
