"""Draft 'I can' descriptors for WI-SS K-5 indicators (K-2 'e', 3-5 'i' and grade-specific codes).
Tuple order: (advanced, at_target, approaching, emerging). Wisconsin/US references are localised to Qatar.
"""
D = {
    # ---------------- Inquiry ----------------
    "SS.Inq1.a.e": ("ask my own question about the topic and explain why it is important.",
                    "explain why or how a question from my teacher or a text is important to a topic.",
                    "say if a question is about our topic, with help.",
                    "repeat a question my teacher asks about the topic."),
    "SS.Inq1.a.i": ("sort my questions into open and closed and choose the best one to research.",
                    "develop a list of open- and closed-ended questions on a topic or issue.",
                    "write one open and one closed question with a sentence starter.",
                    "ask a yes/no question about the topic."),
    "SS.Inq1.b.e": ("plan the order of questions we need to answer to finish our research.",
                    "decide what other questions we need to answer when given a question (What more do we need to know?).",
                    "add one more question to a class question, with help.",
                    "say what I want to know about a picture."),
    "SS.Inq1.b.i": ("explain how each question on my list will help guide my inquiry.",
                    "develop a list of questions through discussion and investigation to guide my inquiry.",
                    "add questions to a class list during discussion, with help.",
                    "ask one question about the topic."),
    "SS.Inq2.a.e": ("explain why a resource I chose would help answer our question.",
                    "brainstorm what resources, such as books, people, and websites, would help our inquiry.",
                    "name one resource that could help, with help.",
                    "point to a book or picture about our topic."),
    "SS.Inq2.a.i": ("gather resources from different types of media and explain which category each fits.",
                    "gather a variety of resources and sort them into categories to guide my inquiry.",
                    "gather two resources and sort them, with help.",
                    "find one book or picture about my topic."),
    "SS.Inq2.b.e": ("explain which source gives the best information for our inquiry.",
                    "review books, photos, artifacts, and websites and ask questions about what they tell us.",
                    "ask one question about a source, with help.",
                    "look at a photo and say what I see."),
    "SS.Inq2.b.i": ("explain why one resource is more useful or reliable than another.",
                    "evaluate resources to decide which best support my inquiry and supporting questions.",
                    "choose the more helpful of two resources, with help.",
                    "say if a source is about my topic."),
    "SS.Inq3.a.e": ("state my own claim and give a reason for it.",
                    "state a claim to answer a class question, with prompting and support.",
                    "finish a sentence starter to state a claim, with help.",
                    "say yes or no to answer a class question."),
    "SS.Inq3.a.i": ("write a clear thesis statement and explain how my evidence supports it.",
                    "create a thesis statement based on evidence from sources to make a claim.",
                    "write a claim using a frame, with help.",
                    "say what I think about the question."),
    "SS.Inq3.b.e": ("explain why a piece of evidence supports the claim better than another.",
                    "decide which evidence in teacher-given sources supports a claim that answers a question.",
                    "point to evidence that matches a claim, with help.",
                    "find a picture that matches the topic."),
    "SS.Inq3.b.i": ("choose the strongest evidence from more than one source to support a claim.",
                    "select appropriate evidence from sources to support a claim.",
                    "select one piece of evidence for a claim, with help.",
                    "find one fact in a source."),
    "SS.Inq3.c.e": ("explain how two pieces of evidence work together to support our claim.",
                    "explain how evidence supports a claim in a class inquiry.",
                    "say because to connect evidence to a claim, with help.",
                    "point to the evidence for our class claim."),
    "SS.Inq3.c.i": ("judge whether my evidence is strong enough and add more if needed.",
                    "assess how well evidence supports a claim.",
                    "say if evidence supports a claim, with help.",
                    "match evidence to a claim using pictures."),
    "SS.Inq4.a.e": ("share my conclusion clearly and add a picture or detail to help others understand.",
                    "communicate my conclusions.",
                    "share my conclusion using a sentence frame, with help.",
                    "draw or point to show what I learned."),
    "SS.Inq4.a.i": ("choose the best presentation option for my audience and explain my choice.",
                    "communicate conclusions using one of the presentation options my teacher gives.",
                    "present my conclusion using a template, with help.",
                    "share one thing I learned with a partner."),
    "SS.Inq4.b.e": ("answer questions about my inquiry and add new details to explain my thinking.",
                    "respond effectively to questions about my inquiry.",
                    "answer a simple question about my work, with help.",
                    "nod or point to answer a question about my work."),
    "SS.Inq4.b.i": ("give helpful feedback on a claim and use feedback to improve my own.",
                    "evaluate the strength of a claim, evidence, and communication using criteria from my teacher and class.",
                    "use a checklist to check a claim, with help.",
                    "say one thing I like about a presentation."),
    "SS.Inq5.a.e": ("suggest a way our class can help our school or community and help carry it out.",
                    "explore ways I can help my community, school, or country by myself or with others.",
                    "name one way to help my school or community, with help.",
                    "help keep my classroom clean."),
    "SS.Inq5.a.i": ("plan a civic action with others and explain how it helps the community or the world.",
                    "explore opportunities to take civic action alone or with others in my community, school, country, or world.",
                    "describe one way people can help their community, with help.",
                    "name a problem in my school or community."),
    # ---------------- Behavioral Sciences ----------------
    "SS.BH1.a.2": ("explain how a change in my relationships or environment could change how I act.",
                   "explain that I am an individual who is influenced by my relationships and environments.",
                   "name one person or place that affects how I act, with help.",
                   "name people who are important to me."),
    "SS.BH1.a.4": ("compare how two different environments affect a person's behavior.",
                   "describe how a person's understanding, perceptions, and behavior are affected by relationships and environments.",
                   "give one example of how friends or family affect a person's behavior, with help.",
                   "say how I act at home and at school."),
    "SS.BH1.b.2": ("explain how I can help someone who feels upset in a situation.",
                   "identify situations and places that affect a person's emotions.",
                   "match a situation to a feeling, with help.",
                   "name a feeling using a picture."),
    "SS.BH1.b.4": ("explain how parts of my identity work together to shape who I am.",
                   "describe how culture, ethnicity, age, religion, gender, and family background can help form self-image and identity.",
                   "name one part of my identity and how it shapes me, with help.",
                   "say my name, age, and one thing about my family."),
    "SS.BH2.a.K-1": ("explain why groups of people can be alike in some ways and different in others.",
                     "describe how groups of people are alike and different.",
                     "name one way two groups are alike or different, with help.",
                     "point to pictures of people who are alike."),
    "SS.BH2.a.4-5": ("explain why two cultures solve the same problem in different ways.",
                     "compare how people from different cultures solve common problems, such as food, shelter, and getting along.",
                     "name one way a culture solves a problem, with help.",
                     "name a basic need such as food or shelter."),
    "SS.BH2.b.1": ("explain how my family adapted to a change and what I learned from it.",
                   "describe ways people change and adapt to new situations in places and in a family.",
                   "name one change my family went through, with help.",
                   "say how I feel about something new."),
    "SS.BH2.b.4": ("explain how different values can lead people to see the same event differently.",
                   "give examples of how people from different cultures develop different values and ways of seeing experiences.",
                   "name one value that is important in a culture, with help.",
                   "name something my family thinks is important."),
    "SS.BH3.a.2": ("explain why a belief or celebration is important in two cultures.",
                   "compare a belief or celebration in one culture with one in a different culture.",
                   "name one way a celebration is different in another culture, with help.",
                   "name a celebration in my family."),
    "SS.BH3.a.5": ("explain how a misunderstanding between cultures could be fixed.",
                   "investigate how similarities and differences between cultures can lead to understanding or misunderstanding.",
                   "give one example of a cultural misunderstanding, with help.",
                   "name a way people from two cultures are different."),
    "SS.BH4.a.e": ("compare how a technology is used for social or cultural purposes in two places.",
                   "describe types of technology and show how they are used every day for social or cultural purposes.",
                   "name a technology and one way people use it, with help.",
                   "point to a technology I use."),
    "SS.BH4.a.i": ("explain how a technology changed people's lives for better and for worse.",
                   "classify technologies by use, access, and design and explain how they might change people's lives.",
                   "sort technologies by what they are used for, with help.",
                   "name two technologies."),
    # ---------------- Economics ----------------
    "SS.Econ1.a.1": ("explain why a resource is important to my family and my country.",
                     "tell the difference between a want and a need and describe resources that are useful to me, my family, community, and country.",
                     "sort pictures into wants and needs, with help.",
                     "name something I need."),
    "SS.Econ1.a.3": ("use costs and benefits to make and defend a decision.",
                     "compare the costs and benefits of a decision and sort limited resources such as money, time, and land.",
                     "name one cost and one benefit of a choice, with help.",
                     "say what I give up when I choose something."),
    "SS.Econ1.b.2": ("explain why a reward changes how different people behave.",
                     "predict how a person's behavior changes in response to different rewards.",
                     "say what a person might do to get a reward, with help.",
                     "name a reward I like."),
    "SS.Econ1.b.4": ("explain how an incentive in a real situation changes people's choices.",
                     "infer possible incentives in a real-world situation.",
                     "name an incentive in a story or situation, with help.",
                     "say what makes me want to do something."),
    "SS.Econ2.a.1": ("explain how one person can be both a buyer and a seller.",
                     "tell the difference between buyers (consumers) and sellers (producers).",
                     "sort people in pictures into buyers and sellers, with help.",
                     "point to a person buying something."),
    "SS.Econ2.a.3-4": ("compare two local markets and explain why people choose one over the other.",
                       "compare two product markets in my community and tell the difference between goods and services.",
                       "name a local market and say if it sells goods or services, with help.",
                       "name a shop in my community."),
    "SS.Econ2.b.2": ("explain why some products cost more than others in a local market.",
                     "define a product market and sort prices of products in a local market.",
                     "sort products into cheap and expensive, with help.",
                     "name something sold in a shop."),
    "SS.Econ2.b.4-5": ("predict how a change, such as a drought or a fad, will affect prices.",
                       "assess the roles of consumers (demand), producers (supply), prices, and competition in a market.",
                       "explain what happens to price when many people want a product, with help.",
                       "say that people buy and sell at a market."),
    "SS.Econ2.c.2": ("explain how a producer uses land, labor, capital, and ideas to earn a profit.",
                     "predict how producers use factors of production to make goods, deliver services, and earn profits.",
                     "name what is needed to make a product, with help.",
                     "name something a person makes."),
    "SS.Econ2.c.3": ("compare the factors of production for two products and explain the differences.",
                     "compare the skills needed to produce goods and services and give an example of the factors of production for a product.",
                     "name a skill needed for a job, with help.",
                     "name a worker and what they make or do."),
    "SS.Econ3.a.1": ("compare the cost of everyday goods in two shops and explain the difference.",
                     "identify the cost of everyday goods such as milk, bread, and fruit.",
                     "read a price tag on an everyday item, with help.",
                     "point to food items in a shop picture."),
    "SS.Econ3.a.4": ("explain why the cost of something changed over time.",
                     "investigate how the cost of things changes over time.",
                     "compare an old and a new price of an item, with help.",
                     "say if something is cheap or expensive."),
    "SS.Econ3.b.1": ("make a saving plan and explain why it helps me.",
                     "sort types of money, explain why money is used, and give reasons why people save.",
                     "name coins and notes and one reason to save, with help.",
                     "point to money in a picture."),
    "SS.Econ3.b.5": ("explain how interest affects saving and borrowing, using a simple example.",
                     "describe the role of money, banking, and saving in everyday life, including why people borrow and the role of interest.",
                     "say why people put money in a bank, with help.",
                     "name a bank or a place to keep money."),
    "SS.Econ4.a.2": ("draw the steps a good takes to reach my local market.",
                     "hypothesize how a good gets to my local community market.",
                     "put pictures of a good's journey in order, with help.",
                     "name a food I buy at a market."),
    "SS.Econ4.a.3": ("explain what happens to a supply chain when one step stops.",
                     "trace the chain of supply for a needed product such as food.",
                     "order the main steps of a supply chain, with help.",
                     "say where food comes from."),
    "SS.Econ4.b.1": ("explain how different jobs and institutions work together to help my community.",
                     "classify jobs and how they help others and explain what public and private institutions do for people.",
                     "match a job or institution to how it helps, with help.",
                     "name a community helper."),
    "SS.Econ4.b.4-5": ("explain how banks or the government help society and compare private and public property.",
                       "assess the role of economic institutions and tell the difference between private and public property.",
                       "sort places into private or public property, with help.",
                       "name a public place like a park."),
    "SS.Econ4.c.2": ("explain what would happen if the government stopped a service.",
                     "summarize goods and services the government provides, such as roads, schools, and police, and how they help people.",
                     "name one government service and how it helps, with help.",
                     "point to a road, school, or police car in a picture."),
    "SS.Econ4.c.5": ("discuss what a government should spend money on and give reasons.",
                     "discuss reasons a government collects money (taxes or fees) from people.",
                     "name one thing a government pays for, with help.",
                     "say that the government pays for schools and roads."),
    "SS.Econ4.d.1": ("explain both a cost and a benefit of an event that were not planned.",
                     "give an example of an unintended cost or benefit of an event.",
                     "say one surprise result of an event, with help.",
                     "say if something was good or bad."),
    "SS.Econ4.d.5": ("predict unintended costs and benefits of a current event and explain who is affected.",
                     "predict unintended costs and benefits (externalities) of a current situation or event.",
                     "name one unplanned effect of a situation, with help.",
                     "name one effect of an event."),
    "SS.Econ4.e.2": ("explain why Qatar trades with other countries and how special skills help people.",
                     "investigate how special skills help people and hypothesize why people in one country trade with another.",
                     "name a special skill and one product Qatar trades, with help.",
                     "name something I am good at."),
    "SS.Econ4.e.3": ("explain why two regions specialize in different products.",
                     "compare and contrast specialization in two or more regions, such as Qatar and Japan.",
                     "name what one region is known for producing, with help.",
                     "name a product from Qatar."),
    # ---------------- Geography ----------------
    "SS.Geog1.a.1": ("choose a map or a globe for a task and explain my choice.",
                     "tell the difference between maps and globes and why someone might choose one for a task.",
                     "point to a map and a globe and say one difference, with help.",
                     "point to a map or a globe."),
    "SS.Geog1.a.4-5": ("explain how Qatar's location affects its people and build a map with all key elements.",
                       "summarize how location affects people, places, and environment, and construct maps, charts, and graphs with title, scale, and legend.",
                       "make a simple map with a title and legend, with help.",
                       "point to Qatar on a map."),
    "SS.Geog1.b.1-2": ("compare two places using maps and photos.",
                       "identify physical and human characteristics of a place using maps, graphs, photos, and other representations.",
                       "name one physical and one human feature in a photo, with help.",
                       "point to land, water, and buildings in a picture."),
    "SS.Geog1.b.i": ("choose the best map or image for a question and explain why.",
                     "identify purposes of and differences among maps, globes, aerial photos, charts, and satellite images.",
                     "match a map or image to its purpose, with help.",
                     "name a map and a photo."),
    "SS.Geog1.c.1": ("draw a map of a familiar place from memory with a key and directions.",
                     "construct a map of a familiar place, such as my classroom, using a title, compass rose, and symbols.",
                     "add symbols to a map of my classroom, with help.",
                     "point to things in my classroom on a map."),
    "SS.Geog1.c.4-5": ("create a labeled map of Qatar with physical and human features and draw its regions.",
                       "create and label a map of my community and country with physical and human features and identify regions.",
                       "label features on a map of Qatar, with help.",
                       "point to Doha on a map of Qatar."),
    "SS.Geog2.a.K-1": ("explain why many people live in Doha and fewer live in the desert.",
                       "analyze where and why people live in certain places and classify my community as rural, suburban, or urban.",
                       "say if a place is a city or the countryside, with help.",
                       "name the place where I live."),
    "SS.Geog2.a.3": ("explain how the population of Qatar is spread across different types of communities.",
                     "categorize the people living in my country and compare rural, suburban, and urban communities and places on Earth.",
                     "name one difference between a city and a village, with help.",
                     "name a city in Qatar."),
    "SS.Geog2.b.2": ("explain different reasons people moved to and away from my community.",
                     "explain why people have moved to and away from my community.",
                     "name one reason people move, with help.",
                     "say where my family lived before."),
    "SS.Geog2.b.5": ("compare push and pull factors for people moving to Qatar and to another country.",
                     "investigate push and pull factors of movement in my community, country, and world.",
                     "name one push and one pull factor, with help.",
                     "say why someone might move to a new place."),
    "SS.Geog2.c.2": ("explain how population changes have changed my community over time.",
                     "describe population changes in my community over time.",
                     "say if my community has more or fewer people now, with help.",
                     "name people who live in my community."),
    "SS.Geog2.c.5": ("explain the causes and effects of population change in Qatar over time.",
                     "describe population changes in my country over time.",
                     "read a simple graph of Qatar's population, with help.",
                     "say that more people live in Qatar now."),
    "SS.Geog2.d.1": ("compare life in rural and urban areas and explain which I prefer and why.",
                     "identify and explain differences between rural and urban areas.",
                     "sort pictures into rural and urban, with help.",
                     "point to a city in a picture."),
    "SS.Geog2.d.4-5": ("explain why cities in Qatar are located where they are and weigh their good and bad points.",
                       "summarize positive and negative factors of cities and identify the location and patterns of cities in my country.",
                       "name one good and one bad thing about cities, with help.",
                       "name a city in Qatar."),
    "SS.Geog3.a.1": ("suggest a fair way to share a resource so there is less stress.",
                     "analyze how different access to resources can create stress in a group.",
                     "say what happens when there is not enough for everyone, with help.",
                     "share a resource with a partner."),
    "SS.Geog3.a.5": ("explain the effects of using renewable and nonrenewable resources locally and globally.",
                     "classify resources as renewable or nonrenewable and analyze what using them means locally, nationally, and globally.",
                     "sort resources into renewable and nonrenewable, with help.",
                     "name a resource like water or oil."),
    "SS.Geog3.b.2": ("explain why a family chooses one kind of transport or communication over another.",
                     "compare and contrast ways of transportation and communication families use for work and daily life.",
                     "name two ways people travel or communicate, with help.",
                     "point to a car, bus, or phone."),
    "SS.Geog3.b.4": ("explain how Qatar depends on other countries and how transport changed trade over time.",
                     "classify ways people and countries depend on each other and summarize how transport and communication changed trade.",
                     "name one thing Qatar gets from another country, with help.",
                     "name something that comes from another country."),
    "SS.Geog4.a.2": ("explain why a special place in my community has meaning for people.",
                     "categorize characteristics of my community and describe places that have special meaning.",
                     "name the weather and one special place in my community, with help.",
                     "name a place in my community."),
    "SS.Geog4.a.4": ("explain why people may view the same place differently.",
                     "describe places with special meanings, compare rural, suburban, and urban places, and describe how people view places differently.",
                     "name a special place and why it matters, with help.",
                     "name a place that is special to me."),
    "SS.Geog5.a.1": ("explain whether a human change near my school helped or harmed the environment.",
                     "give examples of human changes to the environment around my school or neighborhood.",
                     "point to a human change near my school, with help.",
                     "name something people built."),
    "SS.Geog5.a.3-4": ("explain how a human action in Qatar, such as land reclamation, had good and bad effects over time.",
                       "compare the positive and negative effects of human actions on the physical environment over time.",
                       "name one good and one bad effect of a human action, with help.",
                       "say if an action is good for nature."),
    "SS.Geog5.b.2": ("explain how a natural resource in Qatar is used and why it matters.",
                     "identify natural resources of a place and give examples of how they are used.",
                     "name a natural resource and one use, with help.",
                     "point to a natural resource in a picture."),
    "SS.Geog5.b.5": ("suggest ways to reduce harm when people use natural resources.",
                     "examine how human actions change the environment when people use renewable and nonrenewable resources.",
                     "name one way using a resource changes the land or sea, with help.",
                     "name a resource people use."),
    # ---------------- History ----------------
    "SS.Hist1.a.e": ("explain how more than one cause led to an event.",
                     "identify one or more causes of an event, issue, or problem.",
                     "name one cause of an event in a story, with help.",
                     "say what happened first in a story."),
    "SS.Hist1.a.i": ("use evidence from more than one source to explain the most important cause of an event.",
                     "use evidence to draw conclusions about probable causes of historical events.",
                     "find one cause of a historical event in a source, with help.",
                     "name an event from Qatar's history."),
    "SS.Hist1.b.e": ("explain how one event led to more than one effect.",
                     "identify one or more effects of an event, issue, or problem.",
                     "name one effect of an event in a story, with help.",
                     "say what happened next in a story."),
    "SS.Hist1.b.i": ("use evidence from more than one source to explain the most important effect of an event.",
                     "use evidence to draw conclusions about probable effects of historical events.",
                     "find one effect of a historical event in a source, with help.",
                     "say how things changed after an event."),
    "SS.Hist2.a.e": ("explain why some things in my family or community stayed the same over time.",
                     "identify what stayed the same for me, my family, and my community over time.",
                     "name one thing that stayed the same, with help.",
                     "look at an old and a new photo and point to something the same."),
    "SS.Hist2.a.i": ("explain why some traditions in Qatar have continued over time.",
                     "describe patterns of continuity over time in my community and country.",
                     "name one tradition that has continued in Qatar, with help.",
                     "name a tradition in Qatar."),
    "SS.Hist2.b.e": ("explain why something in my family or community changed over time.",
                     "identify patterns of change for me, my family, and my community over time.",
                     "name one thing that changed, with help.",
                     "look at an old and a new photo and point to something different."),
    "SS.Hist2.b.i": ("explain the causes of a pattern of change in Qatar over time.",
                     "describe patterns of change over time in my community and country.",
                     "name one way Qatar has changed, with help.",
                     "say that Qatar looked different long ago."),
    "SS.Hist2.c.e": ("explain how an event outside my home changed my family's daily life.",
                     "explain how something happening outside my home can affect my family.",
                     "name something outside my home that affects my family, with help.",
                     "name something that happens outside my home."),
    "SS.Hist2.c.i": ("explain why a person or group was important to change or continuity in Qatar.",
                     "analyze individuals, groups, and events to understand why their contributions matter to change or continuity.",
                     "name a person and one thing they did, with help.",
                     "name an important person from Qatar's history."),
    "SS.Hist3.a.e": ("compare a person from the past with my life and explain the similarity.",
                     "describe a person or event from the past that connects to my own life.",
                     "name a person from the past and one way they are like me, with help.",
                     "look at a picture from the past."),
    "SS.Hist3.a.i": ("explain how an event in Qatar's history is similar to a current issue.",
                     "compare events in Qatar's history to a current issue or event.",
                     "match a past event to a current event, with help.",
                     "name an event from the past and one from today."),
    "SS.Hist3.b.e": ("explain both viewpoints of an event and why each person feels that way.",
                     "explain why two people can talk about an event from different viewpoints.",
                     "say how two people felt about an event, with help.",
                     "say how I felt about an event."),
    "SS.Hist3.b.i": ("compare two historical perspectives and explain why they differ.",
                     "identify different historical perspectives about people and events in the past.",
                     "name one perspective about a past event, with help.",
                     "say that people can see an event differently."),
    "SS.Hist3.c.e": ("explain how something from the past still affects my community now.",
                     "explain how something from the past can affect my life now.",
                     "name one thing from the past I still use or do, with help.",
                     "name something old in my home."),
    "SS.Hist3.c.i": ("explain how a historical event in Qatar affects life today, with evidence.",
                     "explain how historical events may affect the present.",
                     "name one effect of a past event on today, with help.",
                     "say that the past can change today."),
    "SS.Hist4.a.e": ("explain how the events before a source help me understand it.",
                     "describe the events that led to the creation of a primary source.",
                     "say what was happening when a photo was taken, with help.",
                     "look at a photo and say what is happening."),
    "SS.Hist4.a.i": ("explain how the historical situation affected what a source says.",
                     "describe the historical context of a primary or secondary source.",
                     "say when and where a source was made, with help.",
                     "say if a source is old or new."),
    "SS.Hist4.b.e": ("explain how knowing the audience helps me understand a source.",
                     "identify the intended audience of a primary or secondary source.",
                     "say who a source was made for, with help.",
                     "say who would like a picture or story."),
    "SS.Hist4.b.i": ("explain how the audience shaped what a source includes.",
                     "describe why the intended audience of a primary or secondary source matters.",
                     "name the audience of a source and one reason it matters, with help.",
                     "say who a source was made for."),
    "SS.Hist4.c.e": ("create a primary source about my life and explain why it is a primary source.",
                     "create one primary source about my life, such as a drawing, photo, or journal.",
                     "make a simple primary source with a template, with help.",
                     "draw a picture about my day."),
    "SS.Hist4.c.i": ("explain how the purpose of a source affects what it tells us.",
                     "describe the intended purpose of a specific primary or secondary source.",
                     "say why a source was made, with help.",
                     "say what a source is about."),
    "SS.Hist4.d.e": ("explain how my point of view shows in my source.",
                     "identify the point of view of my own primary or secondary source.",
                     "say whose view my source shows, with help.",
                     "say what I think in my drawing or story."),
    "SS.Hist4.d.i": ("explain how the author's point of view changes the message of a source.",
                     "describe the impact of the author's point of view on a primary or secondary source.",
                     "name the author of a source and what they think, with help.",
                     "say who made a source."),
    # ---------------- Political Science ----------------
    "SS.PS1.a.K-1": ("explain why rules and national symbols are important to my community and country.",
                     "describe symbols, songs, and traditions of my country and explain why rules and laws matter at home, school, and community.",
                     "name a symbol of Qatar and one rule, with help.",
                     "point to the flag of Qatar."),
    "SS.PS1.a.i": ("explain why laws and a constitution protect both the majority and the minority.",
                   "tell the difference between majority rule and minority rights and hypothesize why laws and constitutions exist.",
                   "explain what a majority vote is, with help.",
                   "say why we have class rules."),
    "SS.PS1.b.1-2": ("compare the contributions of two founders of my country and explain which mattered more.",
                     "compare contributions of two or more influential people related to the founding of my country.",
                     "name one founder of Qatar and one thing they did, with help.",
                     "name a leader of Qatar."),
    "SS.PS1.b.4-5": ("explain how key people and ideas such as justice and equality shaped my country's political culture.",
                     "summarize the contributions of important people in early national history and tell the difference between freedom, justice, equality, rights, and responsibilities.",
                     "match key words like rights and responsibilities to examples, with help.",
                     "name an important leader in Qatar's history."),
    "SS.PS2.a.1-2": ("explain how rights and responsibilities go together in class, school, and community.",
                     "compare rights and responsibilities in the classroom, school, and community and classify basic human rights.",
                     "name one right and one responsibility, with help.",
                     "name one class rule."),
    "SS.PS2.a.i": ("explain how people and groups have worked to protect human rights, with an example.",
                   "investigate examples of rights and responsibilities, including the Universal Declaration of Human Rights, and describe basic human liberties.",
                   "name one human right, with help.",
                   "say that everyone should be treated fairly."),
    "SS.PS2.b.2": ("give my opinion about a school issue and explain why it is fair.",
                   "summarize situations where people have rights, freedoms, and equality and develop an opinion about a school or community issue.",
                   "share an opinion with a sentence frame, with help.",
                   "say what I like or do not like."),
    "SS.PS2.b.5": ("compare being a citizen with being a good citizen, using examples from Qatar.",
                   "compare being a citizen of a country with the principles of good citizenship and describe how people become citizens.",
                   "name one quality of a good citizen, with help.",
                   "name one way to help my community."),
    "SS.PS2.c.1-2": ("explain how a group can influence a decision maker at school.",
                     "identify groups in my school and community, compare their rights and responsibilities, and investigate ways people influence decision makers.",
                     "name a group and one of its responsibilities, with help.",
                     "name groups at my school, like students and teachers."),
    "SS.PS2.c.4-5": ("explain how a group organized to gain rights and what changed because of it.",
                     "critique times when groups were denied rights and summarize how people organize to change their communities.",
                     "give one example of people working together for a change, with help.",
                     "say what is fair and unfair."),
    "SS.PS3.a.1": ("explain how voting on a class decision affects everyone in the group.",
                   "describe the effect an action has on a group and express an opinion and vote on a topic in my life.",
                   "vote on a class choice and say why, with help.",
                   "raise my hand to vote."),
    "SS.PS3.a.4-5": ("explain why citizens take part in decisions and my role at different levels of government.",
                     "investigate why citizens participate in elections or public decisions and identify my role in government at different levels.",
                     "name one way citizens take part, with help.",
                     "say that people can vote."),
    "SS.PS3.b.e": ("explain how civic institutions like my school and family help me.",
                   "identify types of media, explain why we have elections, and summarize the roles of civic institutions.",
                   "name a type of media and one civic institution, with help.",
                   "name my school and my family."),
    "SS.PS3.b.3-4": ("explain how media and civic institutions affect my community and elections.",
                     "give examples of how media are used in elections and government, compare roles people play, and analyze roles of civic institutions.",
                     "name one way media share news about government, with help.",
                     "name a newspaper, TV channel, or website."),
    "SS.PS3.c.1": ("compare what governments do at the city, country, and global level.",
                   "compare basic political institutions and the roles they serve, such as making laws and keeping order.",
                   "name one thing the government does, with help.",
                   "name a leader in Qatar."),
    "SS.PS3.c.4-5": ("explain how different levels of government share power in Qatar.",
                     "classify the basic structures and functions of government and summarize basic powers at different levels.",
                     "name one level of government and one job it does, with help.",
                     "name the Emir of Qatar."),
    "SS.PS3.d.1": ("choose the best idea to solve a class problem and explain why.",
                   "predict how people come up with different ideas to solve a problem.",
                   "share one idea to solve a problem, with help.",
                   "say what the problem is."),
    "SS.PS3.d.5": ("compare how two governments solved the same problem.",
                   "give examples of how different governments solve problems.",
                   "name one problem a government solved, with help.",
                   "name a problem in my community."),
    "SS.PS4.a.e": ("explain why two people see the same topic differently and what I think.",
                   "compare and contrast perspectives on the same topic.",
                   "say what two people think about a topic, with help.",
                   "say what I think about a topic."),
    "SS.PS4.a.i": ("build an argument that answers other points of view with evidence.",
                   "compile relevant information to form an argument that considers other points of view.",
                   "list reasons for my opinion, with help.",
                   "give one reason for my opinion."),
    "SS.PS4.b.2": ("explain how a compromise helped both sides.",
                   "give an example of a compromise.",
                   "act out a compromise with a partner, with help.",
                   "take turns with a partner."),
    "SS.PS4.b.5": ("explain how diverse groups can reach agreement on an issue, with an example.",
                   "describe what influences political attitudes and actions and how diverse groups can work toward agreement.",
                   "name one way groups can agree, with help.",
                   "say that people can disagree and still work together."),
}
