"""EE 'At Target' level (Wisconsin Essential Elements for Social Studies) restated as 'I can' statements."""
D = {
    "SS.EE.Inq1": "I can construct meaningful questions about a social studies topic.",
    "SS.EE.Inq2": "I can gather and choose reliable sources about a social studies topic or issue.",
    "SS.EE.Inq3": "I can make a claim to answer an inquiry question.",
    "SS.EE.Inq4": "I can share and critique the conclusions of a claim.",
    "SS.EE.Inq5": "I can take part in civic action on an issue that matters to me.",
    "SS.EE.BH1": "I can examine how people learn, see things, behave, and form identity.",
    "SS.EE.BH2": "I can investigate how people and groups interact with each other.",
    "SS.EE.BH3": "I can examine how behavior and culture can influence people, events, and other cultures.",
    "SS.EE.BH4": "I can examine how a technology has changed over time and how it influences societies or cultures.",
    "SS.EE.Econ1": "I can use economic reasoning, such as costs and benefits, to understand an issue.",
    "SS.EE.Econ2": "I can understand how consumers and producers make decisions and interact.",
    "SS.EE.Econ3": "I can identify how an economy works as a whole, such as prices, jobs, and saving.",
    "SS.EE.Econ4": "I can identify government decisions and how they affect people, businesses, markets, and resources.",
    "SS.EE.Geog1": "I can use geographic tools, such as maps, to explore the world.",
    "SS.EE.Geog2": "I can identify reasons people move and explore population patterns.",
    "SS.EE.Geog3": "I can identify the effects of where resources are found and how places are connected.",
    "SS.EE.Geog4": "I can examine how a place and people's identity are connected.",
    "SS.EE.Geog5": "I can examine how people and the environment affect each other.",
    "SS.EE.Hist1": "I can use historical evidence to find causes and effects.",
    "SS.EE.Hist2": "I can recognize what changed and what stayed the same over time and the context of a historical event.",
    "SS.EE.Hist3": "I can connect past events, people, and ideas to today and identify different perspectives.",
    "SS.EE.Hist4": "I can examine primary and secondary sources to identify their context, audience, purpose, or point of view.",
    "SS.EE.PS1": "I can identify democratic principles and ideals, such as fairness and rule of law.",
    "SS.EE.PS2": "I can identify the differences between a right, a responsibility, and a privilege.",
    "SS.EE.PS3": "I can identify the roles and processes of political and civic institutions.",
    "SS.EE.PS4": "I can use civic literacy skills, such as finding credible sources and compromise.",
}
